refactor:made minor changes
AppkubeCloud/common-workflow-service pull request #1
Opened 2023-12-21 10:12 UTC by shivakarinigi

Moved the query parameters validation just after the event.

2023-12-21 10:43 UTC, Sohailshah20 requested changes

2023-12-21 10:43 UTC, Sohailshah20 commented on workflow/project/delete_usecase.js
Along with null also check for non-empty string

2023-12-21 10:43 UTC, Sohailshah20 commented on workflow/project/getProjectsUsecases.js
check for non-empty string

2023-12-21 10:43 UTC, Sohailshah20 commented on workflow/task/getTaskDetails.js
check for non empty string

2023-12-21 11:14 UTC, shivakarinigi commented on workflow/task/getTaskDetails.js
okay

2023-12-21 11:48 UTC, shivakarinigi commented on workflow/project/delete_usecase.js
completed

2023-12-21 11:48 UTC, shivakarinigi commented on workflow/project/getProjectsUsecases.js
completed

2023-12-21 11:48 UTC, shivakarinigi commented on workflow/task/getTaskDetails.js
completed

2023-12-27 06:47 UTC, Sohailshah20 approved these changes

2023-12-27 06:50 UTC, merged